# Generated by Django 2.2.7 on 2019-11-08 04:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('institute_profile', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Shift',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('spelling', models.CharField(max_length=100)),
                ('number', models.IntegerField()),
            ],
            options={
                'unique_together': {('spelling', 'number')},
            },
        ),
    ]
