# Generated by Django 2.2.7 on 2019-11-08 04:31

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('institute_profile', '0002_shift'),
    ]

    operations = [
        migrations.CreateModel(
            name='Admission',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('photo', models.ImageField(upload_to='')),
                ('roll_no', models.IntegerField()),
                ('reg_no', models.IntegerField()),
                ('fathers_name', models.CharField(max_length=100)),
                ('mothers_name', models.CharField(max_length=100)),
                ('address', models.TextField()),
                ('department', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='institute_profile.Department')),
                ('semester', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='institute_profile.Semester')),
                ('shift', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='institute_profile.Shift')),
            ],
            options={
                'unique_together': {('roll_no', 'reg_no')},
            },
        ),
    ]
