# Generated by Django 2.2.7 on 2019-11-08 05:05

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('institute_profile', '0002_shift'),
        ('techars_section', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Techar_Admission',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('photo', models.ImageField(upload_to='')),
                ('mobile', models.CharField(max_length=15)),
                ('email', models.EmailField(blank=True, max_length=70)),
                ('address', models.TextField()),
                ('Subject', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='institute_profile.Subjects')),
                ('dept', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='institute_profile.Department')),
                ('rank', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='techars_section.Techar_rank')),
            ],
        ),
        migrations.DeleteModel(
            name='Admission',
        ),
    ]
